# Generated by Django 4.2.16 on 2026-06-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users',
         '0003_alter_subscription_author_alter_subscription_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                max_length=254,
                unique=True,
                verbose_name='Адрес электронной почты'),
        ),
    ]
